### ISSUE TITLE
ass_set_storage_size not be called

### ISSUE THREAD

**Issue by realfinder** [pinterf/assrender#7]
as said here https://github.com/libass/libass/issues/591

https://github.com/bubblesub/bubblesub/files/8075536/sample.zip
```
ffms2("sample.mkv")
assrender("sample.ass")
```

![image](https://user-images.githubusercontent.com/2512153/155348878-7f26da8b-d217-45d5-811c-d1c4d43b168a.png)

**Comment by TheOneric** [comment]
To add a bit info:

ASS rendering depends on the videos storage size (i.e. the nominal size without anamorphic de-squeezing). libass has `ass_set_storage_size` to be informed about it *(while the frame size set via `ass_set_frame_size` is for players typically a isotropicly scaled version of the video’s display size, meaning after anamorphic de-squeezing)*. If `ass_set_storage_size` was never called, libass needs to guess a storage size and the above sample is one case where the guessing doesn't work.
In addition to the above shown non-anamorphic sample, this archive also contains an anamorphic sample: [vlc-issue_libass-storage-size.tar.xz](https://code.videolan.org/videolan/vlc/uploads/b54e0761d0d3f4f79b2947ffb83a3b59/vlc-issue_libass-storage-size.tar.xz).

I suspect in absence of additional filters AviSynth always renders at the video’s storage resolution, so calling `ass_set_storage_size` with the same parameters as `ass_set_frame_size` likely works, but that’s untested. When filters are involved, it’s probably a good idea to check and match what AviSynth’s xy-VSFilter backend does.

**Comment by seiya-git** [comment]
![pic](https://user-images.githubusercontent.com/7394323/166234596-fbecd330-0489-4218-a13e-f77befa713c6.png)
with patch

**Comment by realfinder** [comment]
seems ok now, thanks, let see what TheOneric said

**Comment by TheOneric** [comment]
The first commit 93f8f860484b2f75ddd56b1db7e72c73b9090cd6 in #9 seems reasonable enough to me and it matches what a [VapourSynth fork does](https://github.com/AmusementClub/assrender/commit/26a0d286920e0dff9784b6f6c6d85248993dee13), but I'm not familiar with AviSynth and assrenderer’s expectations and constraints.
If it can render both the non-anamorphic 1080p and the anamorphic sample from the previously linked archive ([vlc-issue_libass-storage-size.tar.xz](https://code.videolan.org/videolan/vlc/uploads/b54e0761d0d3f4f79b2947ffb83a3b59/vlc-issue_libass-storage-size.tar.xz)) correctly, there's nothing I can comment on. *(so far only 1080p results were shown)*

**Comment by realfinder** [comment]
I think this ok?
![image](https://user-images.githubusercontent.com/2512153/167527779-dc2c64f8-75d7-4231-9519-3746795801cc.png)
```
ffms2("anamorphic_s720x576_d1024x576.mkv")
assrender("anamorphic_s720x576_d1024x576.ass")
```

**Comment by TheOneric** [comment]
I missed this at first, but actually, your result isn't quite correct even ignoring the font. But the difference is unrelated to subtitle rendering.
The sample video is anamorphic; it is encoded/stored at 720×576 (5:4) but for display should be de-squeezed to 1024×576 (16:9). Your result was not de-squeezed and is still 720×576. This is unrelated to subtitle rendering though (so nothing wrong with the patch) and depending on how exactly you created the screenshot the missing de-squeeze might even be intentional.

**Comment by realfinder** [comment]
> missing de-squeeze might even be intentional

kinda of, anyway it should be the same as vs https://github.com/AmusementClub/assrender/commit/26a0d286920e0dff9784b6f6c6d85248993dee13 so I think it's time for @pinterf to merge the PR and close this

**Comment by TheOneric** [comment]
> @pinterf: So is it safe and nice?

The first commit of #9, most likely yes.
The subproject update in the second commit has one problem (see #9) and also appears to bump the release number (in the same commit even), which I don't know if you want.
